// Visual, motion and wiring contract for the Almanac (Calendar concept D).
// Copy UNCHANGED to tests/browser/almanac-visual.spec.mjs (Almanac phase 0).
//
// Default target: the reference (docs/proposals/calendar-reference/almanac/almanac.html).
// With ALMANAC_APP=1 it runs against the Life app at #/calendar/almanac after
// POST /api/almanac-visual-seed loads almanac/fixture.json and freezes today at 2026-09-24.
// The app must expose window.__almanac in dev builds exactly like the prototype.
//
// Tests are named by phase:  node --test --test-name-pattern="almanac phase 3" tests/browser/almanac-visual.spec.mjs
// Do not edit this file to fit the build; argue in the PR instead.
import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { chromium } from 'playwright';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = process.env.ALMANAC_REPO_ROOT ?? path.resolve(HERE, HERE.includes('docs/proposals') ? '../../../..' : '../..');
const APP = process.env.ALMANAC_APP === '1';
const REF_URL = pathToFileURL(path.join(REPO, 'docs/proposals/calendar-reference/almanac/almanac.html')).href;
const OUT = path.join(REPO, 'docs/proposals/calendar-reference/almanac/compare');
fs.mkdirSync(OUT, { recursive: true });

let browser;
let server;
let appUrl;
before(async () => {
  browser = await chromium.launch({ headless: true });
  if (APP) {
    await import(pathToFileURL(path.join(REPO, 'scripts/prepare-web.mjs')).href);
    const { createStaticServer } = await import(pathToFileURL(path.join(REPO, 'scripts/serve.mjs')).href);
    const { once } = await import('node:events');
    server = createStaticServer({ root: pathToFileURL(path.join(REPO, 'dist/')), apiRoot: pathToFileURL(REPO + '/') });
    server.listen(0, '127.0.0.1');
    await once(server, 'listening');
    appUrl = `http://127.0.0.1:${server.address().port}`;
  }
});
after(async () => { await browser?.close(); server?.close(); });

async function open({ width = 1280, height = 1250, reducedMotion = 'no-preference', settle = 1800 } = {}) {
  const context = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: 2, reducedMotion });
  const page = await context.newPage();
  const errors = [];
  const posts = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => { if (r.method() === 'POST' && r.url().includes('/api/calendar-ghosts')) posts.push(r.postDataJSON()); });
  if (APP) {
    await page.clock.setFixedTime(new Date('2026-09-24T18:05:00+10:00'));
    await page.goto(appUrl);
    await page.locator('#sign-in-passphrase').fill('life-hub-local');
    await page.locator('#sign-in-button').click();
    await page.locator('#app[data-state="ready"]').waitFor();
    assert.equal(await page.evaluate(async () => (await fetch('/api/almanac-visual-seed', { method: 'POST' })).ok), true);
    await page.evaluate(() => { location.hash = '#/calendar/almanac'; });
  } else {
    await page.goto(REF_URL);
  }
  await page.locator('[data-part="almanac"]').waitFor();
  await page.evaluate(() => document.fonts.ready);
  if (settle) await page.waitForTimeout(settle);
  return { context, page, errors, posts };
}
const shot = (page, name) => page.screenshot({ path: path.join(OUT, `${name}.png`) });
const statuses = page => page.locator('[data-part="bead"]').evaluateAll(ns => Object.fromEntries(ns.map(n => [n.getAttribute('data-step'), n.getAttribute('data-status')])));

/* ------------------------------------------------------------------ phase 2: layout */

test('almanac phase 2: summary, lead lines and openings come from the modules', async () => {
  const { context, page, errors } = await open();
  try {
    assert.deepEqual(await page.locator('[data-part="zoom-pills"] button').allTextContents(), ['Day', 'Week', 'Term', 'Year', 'Almanac']);
    assert.equal(await page.locator('[data-part="zoom-pills"] button').nth(4).getAttribute('aria-pressed'), 'true');
    const n = id => page.locator(`[data-part="stat-${id}"] .alm-top__n`).textContent();
    assert.deepEqual([await n('unbooked'), await n('soon'), await n('openings')], ['2', '7', '4']);
    assert.deepEqual(await page.locator('[data-part="lead-line"]').evaluateAll(ns => ns.map(x => x.getAttribute('data-anchor'))),
      ['unsw-conferral', 'vitamin-d', 'term-4', 'solo-travel', 'korea', 'dream-study'], 'most urgent first');
    const st = await statuses(page);
    assert.equal(st['vitamin-d:book-recheck'], 'now', 'window open, nothing booked');
    assert.equal(st['unsw-conferral:gown'], 'now');
    assert.equal(st['korea:passport'], 'soon');
    assert.equal(st['solo-travel:leave'], 'later');
    assert.equal(st['korea:leave'], undefined, 'Korea starts after term: no leave step');
    assert.deepEqual(await page.locator('[data-part="opening"]').evaluateAll(ns => ns.map(x => x.getAttribute('data-want'))),
      ['good-night', 'keep-empty', 'bob', 'newcastle', 'korean']);
    assert.match(await page.locator('[data-want="good-night"] .alm-open__when').textContent(), /Fri 02\/10 · 6–10 pm\s*84%/);
    assert.match(await page.locator('[data-want="newcastle"] .alm-open__when').textContent(), /Mon 05 – Tue 06\/10/);
    const worldExamples = await page.locator('.alm-t-sub').allTextContents();
    assert.ok(worldExamples.filter(t => t.includes('example')).length >= 3, 'example world data is labelled as example');
    assert.ok(await page.locator('[data-part="forecast"]').isVisible());
    assert.ok(await page.locator('[data-part="wall"]').isVisible());
    assert.deepEqual(errors, []);
    await shot(page, 'almanac-1280');
  } finally { await context.close(); }
});

test('almanac phase 2: no two labels collide and nothing leaves its column', async () => {
  const { context, page } = await open();
  try {
    const clashes = await page.evaluate(() => {
      const boxes = [...document.querySelectorAll('.alm-chart text')].map(t => ({ t: t.textContent, b: t.getBoundingClientRect() }));
      const out = [];
      for (let i = 0; i < boxes.length; i++) for (let j = i + 1; j < boxes.length; j++) {
        const a = boxes[i].b, c = boxes[j].b;
        const ox = Math.min(a.right, c.right) - Math.max(a.left, c.left);
        const oy = Math.min(a.bottom, c.bottom) - Math.max(a.top, c.top);
        if (ox > 2 && oy > 2) out.push(`${boxes[i].t} × ${boxes[j].t}`);
      }
      return out;
    });
    assert.deepEqual(clashes, []);
    const spill = await page.evaluate(() => {
      const rule = document.querySelector('.alm-labelrule').getBoundingClientRect().left;
      return [...document.querySelectorAll('.alm-t-lab, .alm-t-sub')].filter(t => Number(t.getAttribute('x')) < 100 && t.getBoundingClientRect().right > rule).map(t => t.textContent);
    });
    assert.deepEqual(spill, [], 'label column text crosses into the chart');
  } finally { await context.close(); }
});

/* ------------------------------------------------------------------ phase 3: motion */

test('almanac phase 3: lead lines draw back from their anchors, beads pop, the tide reveals', async () => {
  const { context, page } = await open({ settle: 0 });
  try {
    const frames = await page.evaluate(async () => {
      const rail = () => Number(document.querySelector('[data-anchor="korea"] .alm-rail').getAttribute('x1'));
      const clip = () => Number(document.querySelector('#alm-reveal rect').getAttribute('width'));
      const out = [];
      const t0 = performance.now();
      while (performance.now() - t0 < 1400) { await new Promise(r => requestAnimationFrame(r)); out.push({ rail: rail(), clip: clip() }); }
      return out;
    });
    const rails = frames.map(f => f.rail);
    for (let i = 1; i < rails.length; i++) assert.ok(rails[i] <= rails[i - 1] + 0.01, 'the Korea line only grows backwards');
    assert.ok(new Set(rails.map(v => v.toFixed(1))).size >= 8, 'a drawn line, not a jump');
    assert.ok(frames.at(-1).clip >= 1198 - 1, 'the tide chart is fully revealed');
    assert.ok(new Set(frames.map(f => f.clip.toFixed(0))).size >= 8, 'the tide reveals over frames');
  } finally { await context.close(); }
});

test('almanac phase 3: reduced motion lands everything at once', async () => {
  const { context, page } = await open({ reducedMotion: 'reduce', settle: 0 });
  try {
    await page.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
    const x1 = await page.locator('[data-anchor="korea"] .alm-rail').evaluate(n => Number(n.getAttribute('x1')));
    const from = await page.locator('[data-anchor="korea"] .alm-rail').evaluate(n => Number(n.dataset.from));
    assert.ok(Math.abs(x1 - from) < 1);
  } finally { await context.close(); }
});

/* ------------------------------------------------------------------ phase 4: wiring */

test('almanac phase 4: a step previews its write, becomes a task, or is marked done', async () => {
  const { context, page, posts } = await open();
  try {
    await page.locator('[data-step="korea:pet-sitter"]').click();
    const pop = page.locator('[data-part="popover"]');
    await pop.waitFor({ state: 'visible' });
    assert.match(await pop.textContent(), /Last safe day 28\/10\/26 · 34 days left/);
    assert.match(await pop.locator('[data-part="write-preview"]').textContent(), /Hammond → Tasks: “Pet sitter for Leo, Maxxie, SJ & Hunter”, due 28\/10\/26 \(the last safe day\)\./);
    await shot(page, 'almanac-popover-1280');
    await pop.getByRole('button', { name: 'Add as task' }).click();
    await page.waitForTimeout(700);
    assert.match(await page.locator('[data-part="toast"]').textContent(), /Written\. Hammond → Tasks/);
    assert.match(await page.locator('[data-step="korea:pet-sitter"]').getAttribute('class'), /is-tasked/);
    if (APP) assert.deepEqual(posts.at(-1), { id: 'alm-korea:pet-sitter', decision: 'accept' });
    await page.locator('[data-step="vitamin-d:book-recheck"]').click();
    await pop.getByRole('button', { name: 'Already done' }).click();
    await page.waitForTimeout(600);
    assert.equal((await statuses(page))['vitamin-d:book-recheck'], 'done');
    assert.equal(await page.locator('[data-part="stat-unbooked"] .alm-top__n').textContent(), '1', 'the headline counts down');
  } finally { await context.close(); }
});

test('almanac phase 4: openings hold time for Corey and draft messages that are never sent', async () => {
  const { context, page, posts } = await open();
  try {
    await page.locator('[data-want="bob"] [data-act="draft"]').click();
    await page.waitForTimeout(300);
    assert.match(await page.locator('[data-want="bob"] [data-part="draft"]').textContent(), /lunch on Monday 28 September/);
    assert.match(await page.locator('[data-part="toast"]').textContent(), /Draft ready for Bob\. Nothing sent\./);
    await page.locator('[data-want="good-night"] [data-act="hold"]').click();
    await page.waitForTimeout(800);
    assert.match(await page.locator('[data-part="toast"]').textContent(), /with Corey, Fri 02\/10 6:00 pm–10:00 pm, tentative and protected/);
    assert.match(await page.locator('[data-want="good-night"]').getAttribute('class'), /is-held/);
    if (APP) assert.ok(posts.every(p => Object.keys(p).sort().join() === 'decision,id'), 'only { id, decision } leaves the browser');
    await shot(page, 'almanac-held-1280');
  } finally { await context.close(); }
});

/* ------------------------------------------------------------------ phase 2 (phone) */

test('almanac phase 2: phone shows lists, never the wide chart, never scrolls sideways', async () => {
  const { context, page } = await open({ width: 390, height: 1000, settle: 800 });
  try {
    assert.equal(await page.locator('[data-part="chart"]').count(), 0);
    assert.equal(await page.locator('[data-part="lead-list"] [data-part="lead-line"]').count(), 6);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await shot(page, 'almanac-390');
  } finally { await context.close(); }
});
