// Visual, motion and wiring contract for the Term River (Calendar concept B, the Term and Year stops).
// Copy UNCHANGED to tests/browser/river-visual.spec.mjs (Term River phase 0).
//
// Default target: the reference (docs/proposals/calendar-reference/term-river/term-river.html).
// With RIVER_APP=1 it runs against the Life app at #/calendar/term after
// POST /api/calendar-visual-seed (the Term River fixture, frozen at Thu 24/09/26 18:05).
// The app must expose window.__termRiver in dev builds exactly like the prototype.
//
// Tests are named by phase:  node --test --test-name-pattern="river phase 3" tests/browser/river-visual.spec.mjs
// Do not edit this file to fit the build; argue in the PR instead.
import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { chromium } from 'playwright';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = process.env.RIVER_REPO_ROOT ?? path.resolve(HERE, HERE.includes('docs/proposals') ? '../../../..' : '../..');
const APP = process.env.RIVER_APP === '1';
const REF_URL = pathToFileURL(path.join(REPO, 'docs/proposals/calendar-reference/term-river/term-river.html')).href;
const OUT = path.join(REPO, 'docs/proposals/calendar-reference/term-river/compare');
fs.mkdirSync(OUT, { recursive: true });

const BOB_RECEIPT = 'Hammond → Life: “Lunch with Bob”, Mon 28/09 12:00 pm–2:00 pm, tentative and protected. Hammond→Clare: keep it clear.';
const TRIP_RECEIPT = 'Hammond → Life: “Blue Mountains day trip” with Corey, Thu 08/10 9:00 am–6:00 pm, tentative and protected.';

let browser;
let server;
let appUrl;
before(async () => {
  browser = await chromium.launch({ headless: true });
  if (APP) {
    await import(pathToFileURL(path.join(REPO, 'scripts/prepare-web.mjs')).href);
    const { createStaticServer } = await import(pathToFileURL(path.join(REPO, 'scripts/serve.mjs')).href);
    const { once } = await import('node:events');
    server = createStaticServer({ root: pathToFileURL(path.join(REPO, 'dist/')), apiRoot: pathToFileURL(REPO + '/') });
    server.listen(0, '127.0.0.1');
    await once(server, 'listening');
    appUrl = `http://127.0.0.1:${server.address().port}`;
  }
});
after(async () => { await browser?.close(); server?.close(); });

async function goToRiver(page) {
  if (APP) await page.evaluate(() => { location.hash = '#/calendar/term'; });
  await page.locator('[data-part="term-river"]').waitFor();
}
async function open({ width = 1280, height = 1100, reducedMotion = 'no-preference', settle = 1400, seed = true } = {}) {
  const context = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: 2, reducedMotion });
  const page = await context.newPage();
  const errors = [];
  const posts = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => { if (r.method() === 'POST' && r.url().includes('/api/calendar-ghosts')) posts.push(r.postDataJSON()); });
  if (APP) {
    await page.clock.setFixedTime(new Date('2026-09-24T18:05:00+10:00'));
    await page.goto(appUrl);
    await page.locator('#sign-in-passphrase').fill('life-hub-local');
    await page.locator('#sign-in-button').click();
    await page.locator('#app[data-state="ready"]').waitFor();
    if (seed) assert.equal(await page.evaluate(async () => (await fetch('/api/calendar-visual-seed', { method: 'POST' })).ok), true);
  } else {
    await page.goto(REF_URL);
  }
  await goToRiver(page);
  await page.evaluate(() => document.fonts.ready);
  if (settle) await page.waitForTimeout(settle);
  return { context, page, errors, posts };
}
const shot = (page, name) => page.screenshot({ path: path.join(OUT, `${name}.png`) });
const frames = (page, ms, probe) => page.evaluate(async ({ ms, probe }) => {
  const f = new Function(`return (${probe})`)();
  const out = [];
  const t0 = performance.now();
  while (performance.now() - t0 < ms) { await new Promise(r => requestAnimationFrame(r)); out.push(f()); }
  return out;
}, { ms, probe: probe.toString() });
const barX = (page, id) => page.evaluate(id => +document.querySelector(`[data-part="term-river"] rect[data-id="${id}"]`)?.getAttribute('x'), id);
const clipW = () => +document.querySelector('#tr-plot rect, clipPath rect')?.getAttribute('width');

/** Visible SVG text: non-empty, not faded out. */
const textAudit = () => {
  const svg = document.querySelector('[data-part="chart"]');
  const box = svg.getBoundingClientRect();
  const { labelW, padR } = window.__termRiver.TR;
  const W = +svg.getAttribute('width');
  const visible = t => t.textContent.trim() && getComputedStyle(t).opacity !== '0' && +(t.getAttribute('opacity') ?? 1) > 0.01;
  const texts = [...svg.querySelectorAll('text')].filter(visible).map(t => ({ t: t.textContent, b: t.getBoundingClientRect(), plot: !!t.closest('[clip-path]') }));
  const clashes = [];
  for (let i = 0; i < texts.length; i++) for (let j = i + 1; j < texts.length; j++) {
    const a = texts[i].b, c = texts[j].b;
    if (Math.min(a.right, c.right) - Math.max(a.left, c.left) > 2 && Math.min(a.bottom, c.bottom) - Math.max(a.top, c.top) > 2) clashes.push(`${texts[i].t} × ${texts[j].t}`);
  }
  const outside = texts.filter(x => x.plot && (x.b.left < box.left + labelW - 1 || x.b.right > box.left + W - padR + 1)).map(x => x.t);
  const card = svg.closest('[data-part="card"]').getBoundingClientRect();
  const vbW = +svg.getAttribute('viewBox').split(/\s+/)[2];
  const fits = vbW === W && box.left >= card.left - 0.5 && box.right <= card.right + 0.5;
  return { attr: W, css: box.width, fits, clashes, outside, scroll: document.documentElement.scrollWidth, inner: innerWidth };
};

/* ------------------------------------------------------------------ phase 2: layout */

test('river phase 2: lanes, week labels and load come from the modules', async () => {
  const { context, page, errors } = await open();
  try {
    assert.match(await page.locator('[data-part="period"] b').textContent(), /^Term 3 → Term 4/);
    assert.match(await page.locator('[data-part="period"] span').textContent(), /T3 W9 – T4 W3/);
    assert.equal(await page.locator('[data-part="zoom-pills"] [data-zoom="term"]').getAttribute('aria-pressed'), 'true');
    assert.deepEqual(await page.locator('[data-part="chart"] [data-part="lane"]').evaluateAll(n => n.map(x => x.dataset.lane)), ['teacher', 'corey', 'scholar', 'friends', 'body']);
    const lanes = await page.evaluate(() => window.__termRiver.lanes());
    assert.ok(lanes.corey.includes('good-night') && lanes.corey.includes('g-day-trip'), 'Corey time is its own lane');
    assert.ok(lanes.scholar.includes('conferral') && lanes.scholar.includes('uow'), 'study lands in Scholar');
    assert.ok(lanes.friends.includes('g-bob') && lanes.friends.includes('g-newcastle'), 'people land in Friends & family');
    assert.ok(lanes.body.includes('gastro'), 'medical lands in Body');
    const all = Object.values(lanes).flat();
    assert.equal(new Set(all).size, all.length, 'every item is in exactly one lane');
    const weekLabels = await page.locator('[data-part="chart"] .tr-t-week').evaluateAll(n => n.filter(t => +(t.getAttribute('opacity') ?? 1) > 0).map(t => t.textContent));
    for (const w of ['T3 W9', 'T3 W10', 'Hol W1', 'Hol W2', 'T4 W1']) assert.ok(weekLabels.includes(w), `week label ${w}`);
    assert.equal(await page.locator('[data-part="ghost"]').count(), 3, 'three Hammond proposals: Bob, Newcastle, the day trip');
    assert.equal(await page.locator('[data-part="load-week"][data-week="2026-09-21"]').count(), 1);
    const w10 = await page.evaluate(() => window.__termRiver.loads.find(l => l.week === '2026-09-21'));
    assert.equal(w10.booked, 8.5);
    assert.equal(await page.locator('[data-part="load-week"][data-week="2026-11-16"]').getAttribute('data-over'), 'true', 'report week is over capacity');
    assert.equal(await page.locator('[data-part="wall"]').count(), 1, 'Korea is a wall');
    assert.deepEqual(errors, []);
    await shot(page, 'river-term-1280');
  } finally { await context.close(); }
});

test('river phase 2: holidays are narrower than school weeks, not squashed away', async () => {
  const { context, page } = await open();
  try {
    const xs = await page.locator('[data-part="chart"] .tr-t-week').evaluateAll(n => Object.fromEntries(n.map(t => [t.textContent, +t.getAttribute('x')])));
    const school = xs['T3 W10'] - xs['T3 W9'];
    const hol = xs['Hol W2'] - xs['Hol W1'];
    assert.ok(hol < school * 0.8 && hol > school * 0.5, `holiday week ${hol.toFixed(0)}px vs school week ${school.toFixed(0)}px`);
  } finally { await context.close(); }
});

test('river phase 2: laid out at its real width; labels never collide or leave the plot', async () => {
  for (const width of [960, 1280, 1600]) {
    const { context, page } = await open({ width });
    try {
      for (const zoom of ['term', 'year']) {
        if (zoom === 'year') { await page.locator('[data-part="zoom-pills"] [data-zoom="year"]').click(); await page.waitForTimeout(900); }
        const r = await page.evaluate(textAudit);
        assert.ok(Math.abs(r.attr - r.css) < 1, `at ${width}px the chart is scaled (${r.attr} drawn, ${r.css} shown)`);
        assert.ok(r.fits, `at ${width}px the chart's viewBox, width and card disagree`);
        assert.deepEqual(r.clashes, [], `labels collide at ${width}px (${zoom})`);
        assert.deepEqual(r.outside, [], `labels leave the plot at ${width}px (${zoom})`);
        assert.ok(r.scroll <= r.inner, `the page scrolls sideways at ${width}px`);
        if (zoom === 'term') {
          const weeks = await page.locator('[data-part="chart"] .tr-t-week').evaluateAll(n => n.filter(t => +(t.getAttribute('opacity') ?? 1) > 0 && /^((T\d|Hol) )?W\d+$|^H\d+$/.test(t.textContent)).length);
          assert.ok(weeks >= 5, `the Term zoom labels weeks, not months, at ${width}px (${weeks} week labels)`);
        }
        if (width === 960) await shot(page, `river-${zoom}-960`);
        if (width === 1280 && zoom === 'year') await shot(page, 'river-year-1280');
      }
    } finally { await context.close(); }
  }
});

test('river phase 2: agent badges and the Today pill never sit on a label', async () => {
  const { context, page } = await open({ width: 960 });
  try {
    for (const zoom of ['term', 'year']) {
    if (zoom === 'year') { await page.locator('[data-part="zoom-pills"] [data-zoom="year"]').click(); await page.waitForTimeout(900); }
    const hits = await page.evaluate(() => {
      const svg = document.querySelector('[data-part="chart"]');
      const texts = [...svg.querySelectorAll('text')].filter(t => t.textContent.trim() && !t.closest('.tr-agent')).map(t => ({ t: t.textContent, b: t.getBoundingClientRect() }));
      const out = [];
      const chips = [...svg.querySelectorAll('.tr-agent')].filter(c => +(c.getAttribute('opacity') ?? 1) > 0);
      const pill = svg.querySelector('[data-part="today"] rect').getBoundingClientRect();
      for (const x of texts) if (!x.t.includes('Today') && Math.min(pill.right, x.b.right) - Math.max(pill.left, x.b.left) > 1 && Math.min(pill.bottom, x.b.bottom) - Math.max(pill.top, x.b.top) > 1) out.push(`${x.t} under the Today pill`);
      for (let i = 0; i < chips.length; i++) for (let j = i + 1; j < chips.length; j++) {
        const a = chips[i].getBoundingClientRect(), b = chips[j].getBoundingClientRect();
        if (Math.min(a.right, b.right) - Math.max(a.left, b.left) > 1 && Math.min(a.bottom, b.bottom) - Math.max(a.top, b.top) > 1) out.push('two badges stacked');
      }
      for (const chip of chips) {
        const c = chip.getBoundingClientRect();
        for (const x of texts) if (Math.min(c.right, x.b.right) - Math.max(c.left, x.b.left) > 1 && Math.min(c.bottom, x.b.bottom) - Math.max(c.top, x.b.top) > 1) out.push(x.t);
      }
      return out;
    });
    assert.deepEqual(hits, [], zoom);
    }
  } finally { await context.close(); }
});

test('river phase 2: phone is the lanes as lists, and never scrolls sideways', async () => {
  const { context, page } = await open({ width: 390, height: 1500 });
  try {
    assert.equal(await page.locator('[data-part="chart"]').count(), 0, 'no wide chart on a phone');
    assert.deepEqual(await page.locator('[data-part="lane-list"] [data-part="lane"]').evaluateAll(n => n.map(x => x.dataset.lane)), ['teacher', 'corey', 'scholar', 'friends', 'body']);
    assert.equal(await page.locator('[data-part="lane-list"] [data-part="ghost"]').count(), 3);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    const p = await page.locator('[data-part="period"]').boundingBox();
    const z = await page.locator('[data-part="zoom-pills"]').boundingBox();
    assert.ok(z.y >= p.y + p.height - 1, 'the zoom pills sit under the period, not beside it');
    assert.ok(p.width > 300, 'the period title has the full width');
    await shot(page, 'river-390');
  } finally { await context.close(); }
});

/* ------------------------------------------------------------------ phase 3: motion */

test('river phase 3: the plot is revealed left to right on entrance', async () => {
  const { context, page } = await open({ settle: 0 });
  try {
    const ws = await frames(page, 1100, clipW);
    const grown = ws.filter((w, i) => i && w > ws[i - 1] + 0.5).length;
    assert.ok(grown >= 8, `the reveal grows over frames (${grown} growing frames)`);
    assert.ok(ws.every((w, i) => !i || w >= ws[i - 1] - 0.01), 'the reveal never shrinks');
  } finally { await context.close(); }
});

test('river phase 3: Term ↔ Year is one continuous tween of the whole chart', async () => {
  const { context, page } = await open();
  try {
    const x0 = await barX(page, 'accreditation');
    await page.locator('[data-part="zoom-pills"] [data-zoom="year"]').click();
    const f = await frames(page, 800, () => ({ t: window.__termRiver.blend(), x: +document.querySelector('[data-part="term-river"] rect[data-id="accreditation"]').getAttribute('x') }));
    const ts = f.map(v => v.t);
    assert.ok(new Set(ts.map(t => t.toFixed(3))).size >= 10, 'the zoom passes through at least 10 in-between frames');
    assert.ok(ts.every((t, i) => !i || t >= ts[i - 1] - 0.02), 'the blend only moves toward Year (overshoot allowed ≤ 0.02)');
    assert.ok(Math.abs(ts.at(-1) - 1) < 0.001, 'it lands on Year');
    const x1 = f.at(-1).x;
    assert.ok(x1 > x0 + 100, 'Accreditation (from 07/09) slides right as the year opens out');
    const mid = f.find(v => v.t > 0.4 && v.t < 0.6);
    assert.ok(mid && mid.x > x0 && mid.x < x1, 'bars move with the blend, not snapping at the end');
    assert.equal(await page.locator('[data-part="zoom-pills"] [data-zoom="year"]').getAttribute('aria-pressed'), 'true');
    assert.match(await page.locator('[data-part="period"] b').textContent(), /Korea/);
    await page.keyboard.press('+');
    await page.waitForTimeout(800);
    assert.ok(Math.abs(await barX(page, 'accreditation') - x0) < 0.5, 'and back to Term exactly');
  } finally { await context.close(); }
});

test('river phase 3: reduced motion lands at once; resizing re-lays out without replaying', async () => {
  const { context, page } = await open({ reducedMotion: 'reduce', settle: 0 });
  try {
    await page.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
    const full = await page.evaluate(() => { const { labelW, padR } = window.__termRiver.TR; return +document.querySelector('[data-part="chart"]').getAttribute('width') - labelW - padR; });
    assert.ok(Math.abs(await page.evaluate(clipW) - full) < 1, 'the plot is drawn immediately');
    await page.locator('[data-part="zoom-pills"] [data-zoom="year"]').click();
    await page.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
    assert.equal(await page.evaluate(() => window.__termRiver.blend()), 1, 'the zoom lands at once');
  } finally { await context.close(); }
  const second = await open();
  try {
    const { page } = second;
    const w1 = await page.locator('[data-part="chart"]').evaluate(s => +s.getAttribute('width'));
    await page.setViewportSize({ width: 1100, height: 1100 });
    const ws = await frames(page, 700, clipW);
    const w2 = await page.locator('[data-part="chart"]').evaluate(s => +s.getAttribute('width'));
    assert.ok(w2 < w1, 'the chart re-lays out for the narrower column');
    const { labelW, padR } = await page.evaluate(() => window.__termRiver.TR);
    assert.ok(ws.slice(-5).every(w => Math.abs(w - (w2 - labelW - padR)) < 1) && ws.every(w => w > 100), 'resizing never replays the reveal');
  } finally { await second.context.close(); }
});

/* ------------------------------------------------------------------ phase 4: wiring */

test('river phase 4: a proposal previews what Accept writes; Accept writes it and the point becomes held', async () => {
  const { context, page, posts } = await open();
  try {
    await page.locator('[data-part="ghost"][data-id="g-bob"]').click();
    const pop = page.locator('[data-part="popover"]');
    await pop.waitFor({ state: 'visible' });
    assert.ok((await pop.locator('[data-part="write-preview"]').textContent()).includes(BOB_RECEIPT));
    await shot(page, 'river-popover-1280');
    await pop.locator('[data-accept="g-bob"]').click();
    await page.waitForTimeout(1000);
    assert.ok((await page.locator('[data-part="toast"]').textContent()).includes(BOB_RECEIPT));
    assert.equal(await page.locator('[data-part="ghost"][data-id="g-bob"]').count(), 0, 'no longer a proposal');
    assert.match(await page.locator('[data-part="item"][data-id="g-bob"]').getAttribute('class'), /is-held/);
    assert.equal(await page.locator('[data-lane="friends"] .tr-agent').count(), 1, 'only Newcastle still carries a badge');
    if (APP) assert.deepEqual(posts, [{ id: 'g-bob', decision: 'accept' }]);
  } finally { await context.close(); }
});

test('river phase 4: the Corey proposal writes a Corey block; Dismiss writes nothing', async () => {
  const { context, page, posts } = await open();
  try {
    await page.locator('[data-part="ghost"][data-id="g-day-trip"]').click();
    assert.ok((await page.locator('[data-part="write-preview"]').textContent()).includes(TRIP_RECEIPT));
    await page.keyboard.press('Escape');
    await page.waitForTimeout(300);
    await page.locator('[data-part="ghost"][data-id="g-newcastle"]').click();
    await page.locator('[data-dismiss="g-newcastle"]').click();
    await page.waitForTimeout(1000);
    assert.match(await page.locator('[data-part="toast"]').textContent(), /Dismissed\. Nothing written\./);
    assert.equal(await page.locator('[data-id="g-newcastle"]').count(), 0, 'a dismissed proposal leaves the river');
    if (APP) assert.deepEqual(posts, [{ id: 'g-newcastle', decision: 'dismiss' }]);
  } finally { await context.close(); }
});

test('river phase 4: what Accept wrote is what the river shows after a reload (app only)', { skip: !APP && 'the reference has no server' }, async () => {
  const { context, page } = await open();
  try {
    await page.locator('[data-part="ghost"][data-id="g-bob"]').click();
    await page.locator('[data-accept="g-bob"]').click();
    await page.waitForTimeout(1200);
    await page.reload();
    await page.locator('#app[data-state="ready"]').waitFor();
    await goToRiver(page);
    await page.waitForTimeout(1400);
    assert.equal(await page.locator('[data-part="ghost"][data-id="g-bob"]').count(), 0);
    assert.match(await page.locator('[data-part="item"][data-id="g-bob"]').getAttribute('class'), /is-held/);
  } finally { await context.close(); }
});
