// Visual, motion and wiring contract for the Tideline week (Calendar concept A).
// Copy UNCHANGED to tests/browser/tideline-visual.spec.mjs (phase 0).
//
// Default target: the reference prototype (docs/proposals/calendar-reference/tideline.html).
// With TIDELINE_APP=1 it runs against the Life app (dist/ served like the other browser specs)
// at #/calendar, after POST /api/calendar-visual-seed loads fixture.json into the mock API.
// The reference passes every test here. The build must too.
//
// App requirements the spec relies on (see VISUAL-SPEC.md "Test hooks"):
// - POST /api/calendar-visual-seed seeds fixture.json and freezes "now" at 2026-09-24T18:05+10:00.
// - In dev builds only, the view exposes window.__tideline = { state, heights(), total, capacity,
//   setBand, accept, dismiss, openPop, closePop, finish, stats } exactly like the prototype.
//
// Tests are named by the plan phase that must make them pass:
//   node --test --test-name-pattern="phase 3" tests/browser/tideline-visual.spec.mjs
// Earlier phases must keep passing. Every selector is a data-part or data-id attribute.
// Add them in the view. Do not edit this file to fit the build; argue in the PR instead.
import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { chromium } from 'playwright';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = process.env.TIDELINE_REPO_ROOT ?? path.resolve(HERE, HERE.includes('docs/proposals') ? '../../..' : '../..');
const APP = process.env.TIDELINE_APP === '1';
const REF_URL = pathToFileURL(path.join(REPO, 'docs/proposals/calendar-reference/tideline.html')).href;
const OUT = path.join(REPO, 'docs/proposals/calendar-reference/compare');
fs.mkdirSync(OUT, { recursive: true });

const BASE = [58, 158, 104, 232]; // Morning, School, After bell, Yours (calendar-bands.js DEFAULT_BANDS)
const TOTAL = 552;
const MIN = 30;
const CAPACITY = [79, 51, 42, 34, 52, 68, 75]; // capacity-model.js on fixture LOGS, Mon..Sun
const SKIP_LINE = 'Sara→Chadwick: skip Thu 24/09 workout (capacity 34%, sore throat).';

let browser;
let server;
let appUrl;

before(async () => {
  browser = await chromium.launch({ headless: true });
  if (APP) {
    await import(pathToFileURL(path.join(REPO, 'scripts/prepare-web.mjs')).href);
    const { createStaticServer } = await import(pathToFileURL(path.join(REPO, 'scripts/serve.mjs')).href);
    const { once } = await import('node:events');
    server = createStaticServer({ root: pathToFileURL(path.join(REPO, 'dist/')), apiRoot: pathToFileURL(REPO + '/') });
    server.listen(0, '127.0.0.1');
    await once(server, 'listening');
    appUrl = `http://127.0.0.1:${server.address().port}`;
  }
});
after(async () => {
  await browser?.close();
  server?.close();
});

async function open({ width = 1280, height = 1120, reducedMotion = 'no-preference' } = {}) {
  const context = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: 2, reducedMotion });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  if (APP) {
    await page.clock.setFixedTime(new Date('2026-09-24T18:05:00+10:00'));
    await page.goto(appUrl);
    await page.locator('#sign-in-passphrase').fill('life-hub-local');
    await page.locator('#sign-in-button').click();
    await page.locator('#app[data-state="ready"]').waitFor();
    const seeded = await page.evaluate(async () => (await fetch('/api/calendar-visual-seed', { method: 'POST' })).ok);
    assert.equal(seeded, true, 'calendar-visual-seed failed');
    await page.evaluate(() => { location.hash = '#/calendar'; });
  } else {
    await page.goto(REF_URL);
  }
  await page.locator('[data-part="tideline"]').waitFor();
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(700); // entrance finished
  return { context, page, errors };
}
const bandHeights = page => page.evaluate(() =>
  ['morning', 'school', 'after', 'yours'].map(id => document.querySelector(`[data-part="band-${id}"]`).getBoundingClientRect().height));
const approx = (a, b, tol = 1) => Math.abs(a - b) <= tol;
const shot = (page, name) => page.screenshot({ path: path.join(OUT, `${name}.png`) });

/* ------------------------------------------------------------------ phase 2: layout */

test('phase 2: week layout, capacity and chrome match the reference', async () => {
  const { context, page, errors } = await open();
  try {
    assert.equal(await page.locator('[data-part="period"] b').textContent(), 'T3 W10 · last week of term');
    assert.deepEqual(await page.locator('[data-part="zoom-pills"] button').allTextContents(), ['Day', 'Week', 'Term', 'Year', 'Almanac']);
    assert.equal(await page.locator('[data-part="zoom-pills"] button').nth(1).getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('[data-part="day-head"]').count(), 7);
    assert.match(await page.locator('[data-part="day-head"][data-date="2026-09-24"]').getAttribute('class'), /is-today/);
    const pct = await page.locator('[data-part="capacity"]').evaluateAll(n => n.map(x => Number(x.dataset.pct)));
    assert.deepEqual(pct, CAPACITY, 'capacity must come from capacity-model.js, not typed in');
    assert.equal(await page.locator('[data-part="over-flag"]').count(), 1);
    assert.ok(await page.locator('[data-part="day-head"][data-date="2026-09-24"] [data-part="over-flag"]').isVisible(), 'Thursday is over and says so');
    assert.match(await page.locator('[data-part="day-head"][data-date="2026-09-24"] .cal-cap__text').textContent(), /34% · sore throat, poor sleep/);
    assert.match(await page.locator('[data-part="day-head"][data-date="2026-09-25"] [data-part="capacity"]').getAttribute('class'), /is-forecast/);
    // Bands at rest
    const h = await bandHeights(page);
    h.forEach((v, i) => assert.ok(approx(v, BASE[i]), `band ${i} is ${v}, want ${BASE[i]}`));
    assert.equal(await page.locator('[data-part="day-body"]').first().evaluate(n => n.getBoundingClientRect().height), TOTAL + 30);
    // Logs never take a slot
    assert.equal(await page.locator('[data-part="chip"]:has-text("breakfast"), [data-part="chip"]:has-text("Diary")').count(), 0);
    assert.match(await page.locator('[data-part="ambient"]').textContent(), /12 notes touched/);
    // Corey is first-class: warm fill, peach ink, the two-ring mark
    const corey = page.locator('[data-id="thu-corey"]');
    assert.equal(await corey.locator('.cal-chip__title').evaluate(n => getComputedStyle(n).color), 'rgb(122, 80, 56)');
    assert.equal(await corey.locator('.cal-mark').count(), 1);
    // Walls, free time, now
    assert.ok(await page.locator('[data-part="day-body"][data-date="2026-09-27"] [data-part="wall"]').isVisible());
    assert.match(await page.locator('[data-part="free"]').textContent(), /4½ h free/);
    const now = await page.locator('[data-part="now-line"]').evaluate(n => parseFloat(n.style.top));
    assert.ok(approx(now, 58 + 158 + 104 + (232 * (18 + 5 / 60 - 17.5)) / 4.5, 1), `now line at ${now}`);
    // Duplicates merged
    assert.equal(await page.locator('[data-id="gastro"]').count(), 1);
    assert.match(await page.locator('[data-id="gastro"] .cal-chip__meta').textContent(), /2 records merged/);
    assert.deepEqual(errors, []);
    await shot(page, 'tideline-1280');
  } finally {
    await context.close();
  }
});

test('phase 2: no chip ever clips its title', async () => {
  const { context, page } = await open();
  try {
    for (const band of [null, 1, 3]) {
      await page.evaluate(b => window.__tideline.setBand(b), band);
      await page.evaluate(() => window.__tideline.finish());
      const bad = await page.locator('.cal-chip').evaluateAll(chips => chips
        .filter(c => c.dataset.density !== 'sliver')
        .map(c => ({ id: c.dataset.id, h: c.querySelector('.cal-chip__title').getBoundingClientRect().height }))
        .filter(x => x.h < 14.5));
      assert.deepEqual(bad, [], `clipped titles with band ${band}`);
    }
  } finally {
    await context.close();
  }
});

test('phase 2: nothing spills out of a narrow day column (the app beside its rail)', async () => {
  // At 1280px the Life shell leaves each day ~115px. A 960px viewport gives the reference the same.
  for (const width of [960, 1280]) {
    const { context, page } = await open({ width });
    try {
      const bad = await page.evaluate(() => {
        const out = [];
        const inside = (el, box, label) => { const r = el.getBoundingClientRect(); if (r.width && (r.right > box.right + 0.5 || r.left < box.left - 0.5)) out.push(label); };
        document.querySelectorAll('[data-part="day-head"]').forEach(h => {
          const b = h.getBoundingClientRect();
          h.querySelectorAll('.cal-tag, .cal-over, .cal-head__num, .cal-vit > span').forEach(x => inside(x, b, `${h.dataset.date} ${x.className || x.textContent}`));
        });
        document.querySelectorAll('[data-part="wall"] .cal-wall__pill').forEach(p => {
          if (p.scrollWidth > p.clientWidth + 1 || p.getBoundingClientRect().height > 22) out.push('wall pill overflows');
          inside(p, p.closest('[data-part="day-body"]').getBoundingClientRect(), 'wall pill leaves its day');
        });
        document.querySelectorAll('.cal-chip').forEach(c => {
          const b = c.getBoundingClientRect();
          c.querySelectorAll('.cal-chip__acts button').forEach(x => { if (getComputedStyle(x.parentElement).display !== 'none') inside(x, b, `${c.dataset.id} button`); });
        });
        document.querySelectorAll('[data-part="tray"] .btn').forEach(x => { if (x.getBoundingClientRect().height > 40) out.push(`tray button wraps: ${x.textContent}`); });
        if (document.documentElement.scrollWidth > innerWidth) out.push(`page scrolls sideways: ${document.documentElement.scrollWidth} > ${innerWidth}`);
        const cal = document.querySelector('[data-part="tideline"]').getBoundingClientRect();
        const last = [...document.querySelectorAll('[data-part="day-head"]')].at(-1).getBoundingClientRect();
        if (last.right > cal.right + 0.5) out.push('the last day is cut off');
        return out;
      });
      assert.deepEqual(bad, [], `at ${width}px`);
      if (width === 960) await shot(page, 'tideline-960');
    } finally {
      await context.close();
    }
  }
});

/* ------------------------------------------------------------------ phase 3: band motion */

test('phase 3: a band springs open in one smooth tween and the stack never changes height', async () => {
  const { context, page } = await open();
  try {
    const frames = await page.evaluate(async () => {
      const read = () => ['morning', 'school', 'after', 'yours'].map(id => document.querySelector(`[data-part="band-${id}"]`).getBoundingClientRect().height);
      document.querySelector('[data-part="band-school"]').click();
      const out = [];
      const t0 = performance.now();
      while (performance.now() - t0 < 600) {
        await new Promise(r => requestAnimationFrame(r));
        out.push({ t: performance.now() - t0, h: read() });
      }
      return out;
    });
    const school = frames.map(f => f.h[1]);
    for (let i = 1; i < school.length; i++) assert.ok(school[i] >= school[i - 1] - 0.01, 'School never shrinks while opening');
    assert.ok(new Set(school.map(v => v.toFixed(1))).size >= 8, 'at least 8 distinct frames: a tween, not a jump');
    for (const f of frames) assert.ok(approx(f.h.reduce((a, b) => a + b, 0), TOTAL, 1.5), `stack height ${f.h} at ${f.t}ms`);
    const mid = frames.find(f => f.t >= 200 && f.t <= 240);
    if (mid) assert.ok(mid.h[1] > 158 && mid.h[1] < TOTAL - 3 * MIN, 'halfway is between rest and open');
    const end = await bandHeights(page);
    assert.ok(approx(end[1], TOTAL - 3 * MIN) && approx(end[0], MIN) && approx(end[2], MIN) && approx(end[3], MIN));
    assert.equal(await page.locator('[data-part="band-school"]').getAttribute('aria-expanded'), 'true');
    assert.equal(await page.locator('[data-part="focus-pills"] button', { hasText: 'School' }).getAttribute('aria-pressed'), 'true');
    // Density follows height
    assert.equal(await page.locator('[data-id="class-2026-09-24-p1"]').getAttribute('data-density'), 'card');
    assert.ok(Number(await page.locator('[data-id="class-2026-09-24-p1"] .cal-chip__meta').evaluate(n => getComputedStyle(n).opacity)) > 0.95);
    assert.equal(await page.locator('[data-id="thu-corey"]').getAttribute('data-density'), 'sliver');
    await shot(page, 'school-1280');
    // Same band again folds back to rest
    await page.locator('[data-part="band-school"]').click();
    await page.waitForTimeout(600);
    (await bandHeights(page)).forEach((v, i) => assert.ok(approx(v, BASE[i])));
  } finally {
    await context.close();
  }
});

test('phase 3: keyboard, focus pills and reduced motion', async () => {
  const { context, page } = await open({ reducedMotion: 'reduce' });
  try {
    await page.locator('[data-part="band-yours"]').focus();
    await page.keyboard.press('4');
    await page.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
    const h = await bandHeights(page);
    assert.ok(approx(h[3], TOTAL - 3 * MIN), 'reduced motion snaps geometry');
    assert.match(await page.locator('[data-part="announcer"]').textContent(), /Yours expanded/);
    await page.keyboard.press('Escape');
    await page.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
    (await bandHeights(page)).forEach((v, i) => assert.ok(approx(v, BASE[i])));
    await page.locator('[data-part="focus-pills"] button', { hasText: 'Yours' }).click();
    await page.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
    assert.ok(approx((await bandHeights(page))[3], TOTAL - 3 * MIN));
    await shot(page, 'yours-1280');
  } finally {
    await context.close();
  }
});

test('phase 3: geometry is never animated by CSS', async () => {
  const { context, page } = await open();
  try {
    const t = await page.locator('.cal-chip, .cal-band, .cal-bg').evaluateAll(ns => ns.map(n => getComputedStyle(n).transitionProperty + ' ' + getComputedStyle(n).transitionDuration));
    for (const v of t) assert.ok(/^all 0s$|^none/.test(v) || !/(top|height|transform)/.test(v), `CSS transition on geometry: ${v}`);
    const stats = await page.evaluate(() => { window.__tideline.setBand(1); return new Promise(r => setTimeout(() => r(window.__tideline.stats()), 600)); });
    assert.ok(stats.p95 < 8, `frame cost p95 ${stats.p95}ms`);
  } finally {
    await context.close();
  }
});

/* ------------------------------------------------------------------ phase 4: ghosts and wiring */

test('phase 4: a proposal previews exactly what Accept writes, then writes it', async () => {
  const { context, page } = await open();
  try {
    const posts = [];
    if (APP) page.on('request', r => { if (r.url().includes('/api/calendar-ghosts')) posts.push(r.postDataJSON()); });
    const workout = page.locator('[data-id="thu-workout"]');
    assert.match(await workout.getAttribute('class'), /has-proposal/);
    assert.match(await workout.locator('[data-part="proposal"]').textContent(), /Sara suggests: skip workout/);
    await workout.click();
    const pop = page.locator('[data-part="chip-popover"]');
    await pop.waitFor({ state: 'visible' });
    assert.ok((await pop.locator('[data-part="write-preview"]').textContent()).includes(SKIP_LINE));
    await shot(page, 'popover-1280');
    await pop.getByRole('button', { name: 'Accept' }).click();
    await page.waitForTimeout(800);
    assert.ok((await page.locator('[data-part="toast"]').textContent()).includes(SKIP_LINE));
    assert.match(await workout.getAttribute('class'), /is-skipped/);
    assert.doesNotMatch(await workout.getAttribute('class'), /has-proposal/);
    assert.equal(await workout.locator('.cal-chip__meta').textContent(), 'Skipped · Sara');
    if (APP) assert.deepEqual(posts, [{ id: 'g-skip', decision: 'accept' }]);
  } finally {
    await context.close();
  }
});

test('phase 4: dismiss writes nothing; Apply all writes every pending ghost once', async () => {
  const { context, page } = await open();
  try {
    // Inline buttons only exist in wide columns; the popover always has them.
    await page.locator('[data-id="g-good"]').click();
    await page.locator('[data-part="chip-popover"] [data-dismiss="g-good"]').click();
    await page.waitForTimeout(400);
    assert.equal(await page.locator('[data-id="g-good"]').count(), 0);
    assert.match(await page.locator('[data-part="toast"]').textContent(), /Dismissed\. Nothing written\./);
    await page.locator('[data-part="apply-all"]').click();
    await page.waitForTimeout(1200);
    assert.match(await page.locator('[data-part="toast"]').textContent(), /3 changes written\./);
    assert.equal(await page.locator('[data-part="ghost"]').count(), 0, 'no dashed ghosts left');
    assert.match(await page.locator('[data-part="due"][data-id="task-josh-y10"]').getAttribute('class'), /is-moved/);
    await shot(page, 'accepted-1280');
  } finally {
    await context.close();
  }
});

/* ------------------------------------------------------------------ phase 2 (phone) */

test('phase 2: phone shows one day with the week strip and never scrolls sideways', async () => {
  const { context, page } = await open({ width: 390, height: 900 });
  try {
    assert.equal(await page.locator('[data-part="day-strip"] button').count(), 7);
    assert.equal(await page.locator('[data-part="day-strip"] button[data-day="2026-09-24"]').getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('[data-part="day-body"]').count(), 1);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await shot(page, 'tideline-390');
    await page.locator('[data-part="day-strip"] button[data-day="2026-09-26"]').click();
    await page.waitForTimeout(600);
    assert.equal(await page.locator('[data-part="day-body"]').getAttribute('data-date'), '2026-09-26');
  } finally {
    await context.close();
  }
});

test('phase 2: no chip clips its meta line', async () => {
  const { context, page } = await open();
  try {
    for (const band of [null, 1, 3]) {
      await page.evaluate(b => window.__tideline.setBand(b), band);
      await page.evaluate(() => window.__tideline.finish());
      const bad = await page.locator('.cal-chip[data-density="card"]').evaluateAll(chips => chips
        .map(c => { const m = c.querySelector('.cal-chip__meta'); const cb = c.getBoundingClientRect(); const mb = m.getBoundingClientRect(); return { id: c.dataset.id, over: mb.bottom - (cb.bottom - 1) }; })
        .filter(x => x.over > 0.5));
      assert.deepEqual(bad, [], `meta cut off with band ${band}`);
    }
  } finally {
    await context.close();
  }
});
