const field=(id,label,required=false,extra={})=>({id,label,required,type:'textarea',...extra});
const mode=(id,label,description=label)=>({id,label,description});
const voice=(id,name,role)=>({id,name,role});
const common=[field('sources','Supplied source text'),field('userContext','Context you want the voices to use')];
const define=(id,name,description,motif,modes,intake,voices)=>({id,name,description,motif,defaultMode:modes[0].id,modes,intake:[...intake,...common],voices});
export const catalog=[
 define('fates','The Three Fates','Live dialectic across generative, critical and strategic voices.','Greek threads',[mode('normal','Normal','Six stops in two cycles of three, with one interrogation break'),mode('sprint','Sprint','Three stops without a break'),mode('long','Long','Twelve stops in three cycles of four, with two breaks')],[field('task','Task to think through',true),field('audience','Audience'),field('constraints','Constraints'),field('success','Success conditions'),field('priorAttempts','Prior attempts')],[voice('lachesis','Lachesis','Strategist and measurer'),voice('clotho','Clotho','Generative spinner'),voice('atropos','Atropos','Critical cutter'),voice('weave','The Weave','Witness and mapper')]),
 define('horizon','The Horizon Council','Map present trajectories against a desired future.','Norse long hall',[mode('full','Full tension map'),mode('brief','Brief map','Alignment, load-bearing choices and data gaps')],[field('focus','Focus area',true),field('timeHorizon','Time horizon',false,{placeholder:'5 to 10 years'}),field('constraints','Known constraints'),field('trajectory','Current trajectory'),field('desiredFuture','Desired future state'),field('tensions','Known tensions'),field('frequencyJustification','Reason for another review within this quarter')],[voice('ketill','Ketill the Hearthkeeper','Near horizon: 6 months to 2 years'),voice('alvar','Alvar the Far-Gazer','Far horizon: 5 to 10 years'),voice('sigrid','Sigrid the Quiet','The Reckoning')]),
 define('refinery','The Refinery','Build, break and reforge a defensible argument.','Chevruta paired interrogation',[mode('full','All three passes'),mode('build','Builder only'),mode('break','Breaker only'),mode('reforge','Reforger only'),mode('build-break','Build and break'),mode('break-reforge','Break and reforge')],[field('claim','Claim or thesis',true),field('context','Argument context',true),field('audience','Audience and standards',true),field('inputType','Input type',false,{type:'select',options:[{value:'raw',label:'Raw claim'},{value:'draft',label:'Existing draft'}]}),field('draft','Existing drafted argument'),field('constraints','Constraints'),field('weaknesses','Known weaknesses')],[voice('builder','Bezalel the Builder','Affirmative Toulmin structure'),voice('breaker','Beruriah the Breaker','Steelmanned structural critique'),voice('reforger','Nechemya the Reforger','Rebuild with acknowledged limits')]),
 define('cartographers','The Cartographers','Turn literature into a purpose-fit knowledge representation.','Mapping',[mode('full','Full synthesis'),mode('focused','Focused extraction'),mode('direct','Direct source mode'),mode('interrogation','Research interrogation','Nine explicit passes over supplied papers')],[field('topic','Topic',true),field('purpose','Purpose of the synthesis',true),field('scope','Scope constraints'),field('audience','Audience'),field('outputFormat','Preferred output format'),field('knownSources','Known Knowledge Hub page IDs or source names')],[voice('surveyor','Captain Josiah Everly the Surveyor','Map the terrain'),voice('miner','Miss Harriet Quarrington the Miner','Extract load-bearing claims'),voice('cartographer','Mr Ambrose Meridith the Cartographer','Map structural relationships')]),
 define('mirror','The Mirror Council','Clarify conflict between behaviour, aspiration and present capacity.','Confucian rectification and reflection',[mode('quick','Quick read'),mode('deep','Deep read')],[field('conflict','Specific choice or values conflict',true),field('domain','Domain'),field('timescale','Time scale',false,{type:'select',options:[{value:'weekly',label:'Actionable this week'},{value:'long-arc',label:'Long arc question'}]}),field('stakes','Stake level'),field('behaviour','Behavioural record'),field('aspirations','Your stated aspirations'),field('constraints','Current capacity and constraints'),field('emotionalState','Emotional state'),field('priorWork','Prior work on the conflict')],[voice('retrospective','Gu Jian the Retrospective','Revealed preferences'),voice('prospective','Wang Yuan the Prospective','Stated aspirations'),voice('present','Zheng Ming the Present','Present tension and capacity')]),
 define('consilium','The Consilium','Deliberate through incompatible ethical standpoints without a verdict.','Roman and medieval advisory chamber',[mode('standard','Standard dialogue'),mode('extended','Extended dialogue','More short turns for higher stakes')],[field('dilemma','Ethical dilemma',true),field('parties','Affected parties',true),field('constraints','Constraints or explicitly none',true),field('priorReasoning','Prior reasoning and ruled-out options'),field('stakes','Stakes and reversibility'),field('tensions','Known tensions'),field('aspirations','Who you have said you want to become')],[voice('principle','Gaius Officius the Principle','Deontological jurist'),voice('consequence','Lucius Eventus the Consequence','Consequentialist strategist'),voice('virtue','Titus Honestus the Virtue','Character and becoming')]),
 define('witness','The Witness','Audit a specific thinking process and calibrate trust in its result.','Zen and Vipassana observation',[mode('standard','Standard audit'),mode('deep','Deep audit')],[field('instance','Specific thinking instance',true),field('timeBoundary','When and over what period'),field('outcome','What the thinking produced'),field('stakes','Stakes and reversibility'),field('concerns','Known concerns'),field('process','Your account of how thinking unfolded')],[voice('trace','Sati the Trace','Descriptive reconstruction'),voice('patterns','Pañña the Pattern Match','Baseline then warranted pattern assessment'),voice('recalibration','Upekkhā the Recalibration','Confidence assessment')]),
 define('tribunal','The Tribunal of Frames','Open three independent reframes of an entrenched problem.','Nested frames and scale',[mode('quick','Quick'),mode('standard','Standard'),mode('deep','Deep')],[field('problem','Problem as stated',true),field('entrenchment','Why it is entrenched',true),field('framing','Your current framing',true),field('priorAttempts','Prior attempts'),field('stakes','Stakes'),field('constraints','Constraints'),field('emotionalLoading','Emotional dimensions')],[voice('inverter','Counselor Frank Delacorte the Inverter','Hidden functional relationship'),voice('scaler','Special Master Ruth Abernathy the Scaler','Downscale and upscale'),voice('context-shifter','Judge Hollis Venable the Context Shifter','Context dissolution')])
];
