import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { catalog, createSession, advance, act, buildPrompt } from '../../netlify/functions/_shared/cognitive-controller.mjs';

const intake = {task:'Design a community library event',focus:'Career direction',constraints:'No relocation',trajectory:'Two years in current role',claim:'Short meetings improve participation',context:'Proposal',audience:'Library committee',topic:'Meeting participation',purpose:'Evidence for a proposal',conflict:'Rest versus volunteering',behaviour:'I volunteered twice',aspirations:'Protect rest',timescale:'weekly',dilemma:'Disclose a scoring error',parties:'Applicant and committee',instance:'Choosing between two venues',timeBoundary:'Yesterday',outcome:'Selected venue A',problem:'Meetings repeatedly overrun',entrenchment:'Three changes have failed',framing:'We need tighter agendas',sources:'Paper A (2020) reports a small experiment. Paper B (2021) reports a contradictory survey.'};
function start(id, mode) { return createSession({id:randomUUID(),owner:'owner',protocolId:id,mode,intake,requestId:randomUUID()}); }
function model(calls) { return async p => { calls.push(p); return {text:p.stage==='dialogue'?'Duty and rights here require honesty. Which obligation can you accept?':'Grounded contribution.',question:p.gate?'What concrete evidence changes this?':null,evidenceIds:[],nextSpeaker:'consequence'}; }; }
async function run(id,mode) { let s=start(id,mode); const calls=[]; for(let n=0;n<490&&s.status!=='completed';n++){ if(s.status==='queued') s=await advance(s,{model:model(calls),retrieve:async()=>({evidence:[],status:'No matching notes; self-report only.'})}); else if(s.status==='waiting'){let action=s.checkpoint.kind==='reflection'?'reflect':s.checkpoint.kind==='verify'?'confirm':s.allowedActions.includes('finish')?'finish':s.allowedActions.includes('confirm')?'confirm':'answer';s=act(s,{action,text:'Concrete answer',revision:s.revision,requestId:randomUUID()});} else throw Error(s.status); } return {s,calls}; }
for(const id of ['fates','horizon','refinery','cartographers','mirror','consilium','witness','tribunal']) test(`${id} completes with independent calls and no model-owned transitions`,async()=>{const {s,calls}=await run(id,id==='fates'?'sprint':undefined);assert.equal(s.status,'completed');assert.ok(calls.length>=3); assert.equal(s.protocolId,id);});
test('every required intake field is machine-enforced',()=>{for(const d of catalog)for(const f of d.intake.filter(f=>f.required)){assert.throws(()=>createSession({id:randomUUID(),owner:'owner',protocolId:d.id,intake:{...intake,[f.id]:''},requestId:randomUUID()}),/required/);}});
test('Fates quotas, cycle lengths and breaks differ by mode',async()=>{for(const [mode,stops,questions,breaks] of [['sprint',3,2,0],['normal',12,4,1],['long',18,5,2]]){const {calls}=await run('fates',mode);assert.equal(calls.filter(c=>c.stage.startsWith('cycle')).length,stops*questions);assert.equal(new Set(calls.filter(c=>c.stage.startsWith('interrogation')).map(c=>c.stage)).size,breaks);}});
test('checkpoint blocks advance until answered; Witness corrections are reverified',async()=>{let s=start('witness');const calls=[];s=await advance(s,{model:model(calls),retrieve:async()=>({evidence:[],status:'none'})});assert.equal(s.checkpoint.kind,'verify');assert.equal(calls.length,1);assert.deepEqual(await advance(s,{model:model(calls)}),s);s=act(s,{action:'correct',text:'I compared both venues first',revision:s.revision,requestId:randomUUID()});s=await advance(s,{model:model(calls)});assert.equal(s.checkpoint.kind,'verify');assert.equal(calls.length,2);assert.equal(calls[1].stage,'trace');assert.throws(()=>act(s,{action:'finish',revision:s.revision,requestId:randomUUID()}));s=act(s,{action:'uncertain',revision:s.revision,requestId:randomUUID()});s=await advance(s,{model:model(calls)});assert.equal(s.status,'completed');assert.match(calls.find(c=>c.stage==='patterns').system,/sound thinking|Sound thinking/);assert.match(calls.find(c=>c.stage==='patterns').user,/uncertain/);});
test('checkpoint voices keep their analysis and extract a final question',async()=>{let s=start('fates','sprint');s=await advance(s,{model:async()=>({text:'The decision has two live tensions. Which constraint should govern the first pass?',evidenceIds:[]}),retrieve:async()=>({evidence:[],status:'none'})});assert.equal(s.status,'waiting');assert.equal(s.checkpoint.question,'Which constraint should govern the first pass?');assert.match(s.transcript.at(-1).text,/two live tensions/);});
test('JSON voice output supplies the checkpoint question instead of failing the gate',async()=>{
  const retrieve=async()=>({evidence:[],status:'none'});
  const payload={text:'The decision has two live tensions around audience and time.',question:'Which constraint should govern the first pass?',evidenceIds:[]};
  for(const text of [JSON.stringify(payload),`\`\`\`json\n${JSON.stringify(payload,null,2)}\n\`\`\``]){
    let s=start('fates','sprint');
    s=await advance(s,{model:async()=>({text,evidenceIds:[]}),retrieve});
    assert.equal(s.status,'waiting');
    assert.equal(s.checkpoint.question,'Which constraint should govern the first pass?');
    assert.match(s.transcript.at(-1).text,/two live tensions/);
    assert.equal(s.transcript.at(-1).text.includes('{"text"'),false);
  }
  let s=start('fates','sprint');
  await assert.rejects(()=>advance(s,{model:async()=>({text:JSON.stringify({text:'Only analysis.',question:null,evidenceIds:[]}),evidenceIds:[]}),retrieve}),/omitted its required checkpoint question/);
});
test('Tribunal voices receive identical original context and cannot see outputs',async()=>{const {calls}=await run('tribunal');const v=calls.filter(c=>['inverter','scaler','context-shifter'].includes(c.speaker));assert.equal(v.length,3);assert.equal(v[0].user,v[1].user);assert.equal(v[1].user,v[2].user);assert.ok(!v[2].user.includes('Grounded contribution'));});
test('Consilium adapts to next-speaker proposal, never Virtue first, and never analyses final reflection',async()=>{let s=start('consilium');const calls=[];const generate=async p=>{calls.push(p);return {text:'Duty and rights here require candour. Which constraint matters?',question:'Which constraint matters?',evidenceIds:[],nextSpeaker:'virtue'};};s=await advance(s,{model:generate,retrieve:async()=>({evidence:[],status:'none'})});assert.equal(calls.length,1);s=act(s,{action:'confirm',revision:s.revision,requestId:randomUUID()});s=await advance(s,{model:generate});assert.notEqual(calls.at(-1).speaker,'virtue');s=act(s,{action:'answer',text:'Protect anonymity',revision:s.revision,requestId:randomUUID()});s=await advance(s,{model:generate});assert.equal(calls.at(-1).speaker,'virtue');assert.ok(!s.allowedActions.includes('finish'));const {s:done,calls:all}=await run('consilium');assert.equal(done.transcript.at(-1).role,'user');assert.equal(all.at(-1).stage,'map');});
test('direct sources skip search and Surveyor; partial Refinery skips excluded voices',async()=>{let s=start('cartographers','direct');const calls=[];s=await advance(s,{model:model(calls),retrieve:()=>{throw Error('search must not run');}});assert.equal(s.status,'completed');assert.deepEqual(calls.map(c=>c.speaker),['miner','cartographer']);for(const [mode,expected] of [['break',['breaker']],['build-break',['builder','breaker']]]){const {calls}=await run('refinery',mode);assert.deepEqual(calls.map(c=>c.speaker),expected);}});
test('Mirror deep waits for framing, long arc asks what to protect; Horizon fallback explicit',async()=>{const {calls}=await run('mirror','deep');assert.equal(calls[0].stage,'framing');const s=start('mirror');s.intake.timescale='long-arc';assert.match(buildPrompt(s,{speaker:'present',stage:'present'}).system,/sit with, tolerate|protect/);const h=start('horizon');assert.match(buildPrompt(h,{speaker:'alvar',stage:'alvar'}).system,/extrapolated from current trajectory/);});
test('unverified quotes are rejected, and terminal state cannot be model-commanded',async()=>{let s=start('tribunal');await assert.rejects(()=>advance(s,{retrieve:async()=>({evidence:[],status:'none'}),model:async()=>({text:'Claim',quotes:[{evidenceId:'fake',text:'made up'}],evidenceIds:['fake']})}),/evidence|quotation/);});
